categorical_features:
  - workclass
  - education
  - marital_status
  - occupation
  - relationship
  - race
  - sex
  - native_country
modeling_specs:
  random_forest:
    random_seed: 42
    n_estimators: 100
    max_depth: 7
    n_jobs: 2
    criterion: entropy
    max_features: 0.4
